-- 0002_seed_practices.sql
-- Seed global practices from practices.seed.json (generated)
-- Idempotent: uses ON CONFLICT DO UPDATE

insert into public.practices (
  id, title, instruction, mode, difficulty, duration_seconds, contra_notes, created_at, updated_at
) values
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a01'::uuid,
   'Five Sounds, No Labels',
   'Notice five distinct sounds. For each one, stay with the raw texture of the sound without naming its source.',
   'perception', 1, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a02'::uuid,
   'One Object, Become New',
   'Pick a completely ordinary object. Look at it until you notice three details you have never noticed before.',
   'perception', 1, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a03'::uuid,
   'Contact Points Inventory',
   'Notice every place your body touches something: chair, floor, clothing, air. Count at least six distinct contact points.',
   'somatic', 1, 150, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a04'::uuid,
   'Edge of Vision',
   'Keep your gaze soft and notice the edges of your visual field. Hold awareness of the centre and the periphery at the same time.',
   'open', 2, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a05'::uuid,
   'Three Textures',
   'Touch three different surfaces. Notice how each texture changes as you move from fingertip to palm to the back of the hand.',
   'somatic', 1, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a06'::uuid,
   'Pre-Thought Emotion Check',
   'For 60 seconds, notice the first emotional tone in your body before any story forms. Name nothing; just detect the direction (tightening, opening, buzzing, heaviness).',
   'somatic', 2, 120, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a07'::uuid,
   'Single Point: A Sound',
   'Choose one continuous sound (fan, traffic, distant voices). Keep attention with it, and each time you drift, return to the sound’s shape.',
   'focus', 2, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a08'::uuid,
   'Micro-Delay Before Reacting',
   'Think of a small irritation from today. Replay it briefly and insert a one-second pause right before the reaction.',
   'focus', 3, 150, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a09'::uuid,
   'Name-to-Sensation Swap',
   'When a label appears (“annoyed”, “tired”, “fine”), drop the label and look for the sensation it refers to. Stay with the sensation for 10 seconds.',
   'open', 3, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a10'::uuid,
   'Slow Walk: Heel to Toe',
   'Walk slowly for two minutes. Put attention on the sequence: heel contact, weight shift, toe release.',
   'somatic', 1, 120, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a11'::uuid,
   'Two-Minute Listening (Relational)',
   'In your next conversation, listen for two minutes with full attention. Notice the urge to respond, and let it wait until the other person finishes.',
   'relational', 2, 120, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a12'::uuid,
   'Face Without Story',
   'Look at a face (photo or person) and notice shapes, shadows, and movement without constructing a narrative. Treat it like an unfamiliar landscape.',
   'perception', 3, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a13'::uuid,
   'Narrow-to-Wide Attention',
   'Start by focusing on one sensation for 30 seconds. Then widen to include sounds, sights, and body sensations all at once.',
   'open', 2, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a14'::uuid,
   'Impulse Surf (Mild)',
   'Notice a mild impulse (check phone, snack, tab switch). Watch it rise and fall for 20 seconds without acting on it.',
   'focus', 3, 120, 'Choose only a mild impulse. If this increases distress, stop and do a sensory practice instead.', now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a15'::uuid,
   'Room Scan: What Pulls You?',
   'Scan the room and notice what grabs your attention first. Ask: is it brightness, motion, threat, comfort, or curiosity?',
   'perception', 2, 150, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a16'::uuid,
   'Body Weather Report',
   'Notice your body like weather: pressure, temperature, movement, stillness. Identify two “fronts” (e.g., tight jaw + warm hands).',
   'somatic', 2, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a17'::uuid,
   'Unfinished Sentence',
   'Complete this silently: “Right now, what I most want is …” Then notice what changes in your body after the sentence lands.',
   'open', 3, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a18'::uuid,
   'Tension Localisation',
   'Find the strongest tension in your body. Zoom in: does it have edges, pulses, heat, or movement?',
   'somatic', 2, 150, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a19'::uuid,
   'One Task, One Channel',
   'For three minutes, do one simple task with full attention (wash a cup, fold clothing, tidy one surface). Notice each micro-movement.',
   'focus', 2, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a20'::uuid,
   'The Urge to Explain',
   'Notice when your mind starts explaining an experience. Pause the explanation and return to what is directly present for 10 seconds.',
   'open', 3, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a21'::uuid,
   'Mild Discomfort Hold',
   'Choose a mild discomfort (standing still, cool air, slight awkwardness). Stay with it for 30 seconds and observe its changing shape.',
   'somatic', 4, 120, 'Keep it mild. Do not use injury pain or intense distress. Stop if it escalates.', now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a22'::uuid,
   'Attention Hand-Off',
   'Pick two senses (sound and sight, or touch and sound). Switch attention between them every 10 seconds without rushing.',
   'focus', 2, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a23'::uuid,
   'Tiny Gratification Delay',
   'Pick a tiny gratification you were about to take (scroll, snack, refresh). Delay it by 30 seconds and notice what the delay reveals.',
   'focus', 3, 120, 'Keep it small. This is not a willpower challenge; stop if it becomes a struggle.', now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a24'::uuid,
   'Three Micro-Choices',
   'Over the next hour, notice three micro-choices you make automatically. For each, pause for one second before doing it.',
   'open', 3, 120, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a25'::uuid,
   'Listen for the Quietest Sound',
   'Search for the quietest sound you can detect. When you find it, hold attention there and notice how it changes.',
   'perception', 2, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a26'::uuid,
   'One Minute of Direct Eye Contact',
   'If appropriate and comfortable, hold gentle eye contact for one minute during a conversation. Notice any urge to look away and what it signals.',
   'relational', 4, 60, 'Only do this in safe, normal contexts. Skip if it feels intrusive or unsafe.', now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a27'::uuid,
   'Speech as Sound',
   'For 60 seconds, listen to speech as pure sound: rhythm, pitch, speed, pauses. Let meaning be secondary.',
   'relational', 3, 120, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a28'::uuid,
   'Hands: Temperature Gradient',
   'Notice temperature differences across your hands: fingertips, knuckles, palm, wrist. Track where warmth begins and ends.',
   'somatic', 1, 150, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a29'::uuid,
   'Attention as a Spotlight',
   'Imagine attention as a spotlight you can steer. Move it deliberately: sound → hands → sight → back to sound.',
   'focus', 2, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a30'::uuid,
   'The First Thought After Silence',
   'Create a brief moment of silence (no inputs). Notice the very first thought that appears and what it tries to do.',
   'open', 3, 120, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a31'::uuid,
   'Spot the Background Effort',
   'Notice any subtle effort you’re carrying: bracing, holding, clenching, rushing. Let one small effort reduce by 10%.',
   'somatic', 3, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a32'::uuid,
   'Colour Temperature Hunt',
   'Look for three different colour temperatures around you (cool, neutral, warm). Notice how each changes the feeling of a space.',
   'perception', 2, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a33'::uuid,
   'Minute of Not Fixing',
   'Pick a minor problem you keep mentally fixing. For one minute, let the problem exist without solving it and notice what arises.',
   'open', 4, 120, 'Use only minor issues. Skip anything that feels urgent or high-stakes.', now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a34'::uuid,
   'Micro-Awe Scan',
   'Find one small detail that is unexpectedly intricate (a leaf vein, a fabric weave, a circuit pattern). Stay with it until it feels slightly vast.',
   'perception', 2, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a35'::uuid,
   'Relational: Listen for Need',
   'In a conversation, listen for what the other person may be needing (clarity, reassurance, space, recognition). Don’t act on it—just notice it.',
   'relational', 3, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a36'::uuid,
   'Notice the Want Behind the Want',
   'Pick something you want right now. Ask once: what is the deeper want beneath it (comfort, certainty, connection, status, rest)?',
   'open', 4, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a37'::uuid,
   'Sound Distance Layering',
   'Identify one near sound, one mid-distance sound, and one far sound. Hold all three in awareness at the same time.',
   'open', 3, 180, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a38'::uuid,
   'Neutral Face, Neutral Story',
   'Notice a neutral expression (your own reflection works). Watch how your mind assigns meaning to it, then return to the raw shapes again.',
   'perception', 3, 150, null, now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a39'::uuid,
   'Two-Minute Waiting Room',
   'For two minutes, do nothing except notice what tries to fill the space. Track: restlessness, planning, scanning, or drifting.',
   'open', 4, 120, 'If restlessness becomes intense, switch to a sensory practice (sounds or contact points).', now(), now()),
  ('b3b9a3b2-7f4e-4e3a-8c5c-1e3c8f1d0a40'::uuid,
   'Value Signal Spotting',
   'Recall a moment from today that tugged at you (pleasant or unpleasant). Identify the value signal inside it: care, fairness, belonging, competence, freedom, or safety.',
   'focus', 4, 180, null, now(), now())
on conflict (id) do update
set
  title = excluded.title,
  instruction = excluded.instruction,
  mode = excluded.mode,
  difficulty = excluded.difficulty,
  duration_seconds = excluded.duration_seconds,
  contra_notes = excluded.contra_notes,
  updated_at = now();

